import hashlib,json
from pathlib import Path
root=Path(__file__).parent;data=json.loads((root/'synthetic-v3.json').read_text());cases=data['cases'].copy();start=len(cases)
def add(family,q,food=None,value=None,unit=None,attrs=None,route='search',reason=None,group=None):
 cases.append({'id':f'nlp-{len(cases)+1:03}','family':family,'scenario_group':group or f'v4-{len(cases)+1:03}','query':q,'expected':{'food':food,'attributes':attrs or {},'quantity':None if value is None else {'value':value,'unit':unit},'route':route,'reason':reason},'invariants':['preserve_original_query','explicit_selection_and_confirmation','no_invented_nutrition','no_inferred_density_or_serving_weight']})
for q,f,v,u in [('¼ banana','banana',.25,'count'),('¾ avocado','avocado',.75,'count'),('2½ apples','apple',2.5,'count'),('1 1/2 banana','banana',1.5,'count'),('3/4 avocado','avocado',.75,'count'),('1/4kg butter','butter',250,'g'),('½l kefir','kefir',500,'ml'),('.125 kg rice','rice',125,'g'),('1,250g potato','potato',1250,'g'),('2,000 ml water','water',2000,'ml'),('100\u00a0g spinach','spinach',100,'g'),('１００g tofu','tofu',100,'g'),('100Ｇ tofu','tofu',100,'g'),('two clementines','clementine',2,'count'),('three boiled eggs','egg',3,'count'),('an apple','apple',1,'count')]:add('number_notation_v4',q,f,v,u)
for q in ['−½ banana','–7g oats','—8ml kefir','−0.2kg rice','-2 eggs','0 bananas','0/4 apple','1/0 apple','0.000g spinach','-0% fat yoghurt','NaN g tofu','Infinityml water']:
 # Negative zero fat is numerically zero, with unknown food quantity: preserve valid zero-percent variant.
 if q=='-0% fat yoghurt':add('signed_zero_variant',q,'yoghurt',attrs={'fat_percent':0})
 else:add('invalid_number_v4',q,route='reject',reason='invalid_quantity')
for q in ['100–200g chicken','150—200g rice','1,5kg rice','1.2.3g rice','2/3/4 apple','1/2/3kg rice','up to 2 eggs','at least 50g lentils','roughly half a banana','approximately 120ml kefir','about 10% fat yoghurt','5% or 10% fat yoghurt','10% fat or 5% fat yoghurt','raw roasted turkey','one jar hummus','a tub yoghurt','a can beans','one bag crisps','one packet noodles','one piece cheese','two handfuls nuts','a small glass kefir','one ladle soup','one scoop protein powder 30g','100g chicken with 50g rice','120g whole milk skimmed','120g dairy-free cheese','80g plant-based burger','40% reduced fat cheddar','£3.99 sandwich','Lunch: chicken and rice','50g yoghurt plus 10g honey']:
 add('scope_and_portion_v4',q,route='clarify',reason='scope_or_identity_requires_review')
for q,f,v,u,a in [('Acme yoghurt 7.5% fat 95g','yoghurt',95,'g',{'brand':'Acme','fat_percent':7.5}),('9.0 percent fat Greek yoghurt 140g','greek yoghurt',140,'g',{'fat_percent':9}),('8g 70 percent dark chocolate','dark chocolate',8,'g',{'cocoa_percent':70}),('16g 100% peanut butter','peanut butter',16,'g',{'ingredient_percent':100}),('90g cooked weight tofu','tofu',90,'g',{'preparation':'cooked','weight_basis':'cooked'}),('1.25L unsweetened oat milk','oat milk',1250,'ml',{'sweetening':'unsweetened'})]:add('attributes_v4',q,f,v,u,a)
assert len({c['query'] for c in cases[start:]})==len(cases[start:]);assert not {c['query'] for c in cases[:start]}&{c['query'] for c in cases[start:]}
data.update(status='synthetic_development_challenge',origin='v3 retained verbatim; additional invented boundary scenarios',cases=cases)
p=root/'synthetic-v4.json';p.write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n');m={'schema_version':1,'fixture':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'case_count':len(cases),'new_case_count':len(cases)-start,'independent_holdout':False,'parser_sha256_before_first_run':hashlib.sha256((root.parent.parent/'Packages/FoodLedgerKit/Sources/FoodLedgerApplication/FoodQueryParser.swift').read_bytes()).hexdigest()};(root/'manifest-v4.json').write_text(json.dumps(m,indent=2)+'\n');print(m)
